

import java.awt.event.ActionListener;
import java.util.List;
import java.util.ListIterator;
import javax.swing.JOptionPane;

import services.Article;
import services.IService1;

import services.Service1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class fenetre extends javax.swing.JFrame {

    /**
     * Creates new form fenetre
     */
    public fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTexte = new javax.swing.JTextArea();
        ChargerBtn = new javax.swing.JButton();
        btnLike = new javax.swing.JButton();
        btnDislike = new javax.swing.JButton();
        btnPremierArticle = new javax.swing.JButton();
        btnDernierArticle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLikes = new javax.swing.JTextField();
        jTextFieldDislikes = new javax.swing.JTextField();
        jTextFieldRecherche = new javax.swing.JTextField();
        btnChercher = new javax.swing.JButton();
        btnArticleSuivant = new javax.swing.JButton();
        btnArticlePrecedent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fenetre Articles");

        jLabelTitre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(51, 51, 255));
        jLabelTitre.setText("Ensemble des articles ");

        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTexte.setEditable(false);
        jTexte.setColumns(20);
        jTexte.setRows(5);
        jScrollPane2.setViewportView(jTexte);

        ChargerBtn.setText("Charger les articles");
        ChargerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargerBtnActionPerformed(evt);
            }
        });

        btnLike.setText("Like");
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });

        btnDislike.setText("Dislike");
        btnDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDislikeActionPerformed(evt);
            }
        });

        btnPremierArticle.setText("Premier Article");
        btnPremierArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierArticleActionPerformed(evt);
            }
        });

        btnDernierArticle.setText("Dernier Article");
        btnDernierArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierArticleActionPerformed(evt);
            }
        });

        jTextFieldLikes.setBackground(new java.awt.Color(102, 255, 0));

        jTextFieldDislikes.setBackground(new java.awt.Color(255, 51, 0));

        btnChercher.setText("Chercher Article");
        btnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherActionPerformed(evt);
            }
        });

        btnArticleSuivant.setText("Article Suivant");
        btnArticleSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleSuivantActionPerformed(evt);
            }
        });

        btnArticlePrecedent.setText("Article Precedent");
        btnArticlePrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticlePrecedentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLike)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextFieldDislikes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDislike)
                                .addGap(50, 50, 50)
                                .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChercher))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDernierArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChargerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPremierArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnArticlePrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnArticleSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChargerBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLike)
                        .addComponent(btnDislike)
                        .addComponent(jTextFieldLikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDislikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChercher)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremierArticle)
                    .addComponent(btnArticlePrecedent)
                    .addComponent(btnArticleSuivant)
                    .addComponent(btnDernierArticle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChargerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargerBtnActionPerformed
       
       
       jComboBox1.removeAllItems();
     
         liste = service.getAllArticles().getArticle();
       
        
      
       if(liste.isEmpty())
       {
       JOptionPane.showMessageDialog(this, "Aucun article trouve");
       return;}
       jComboBox1.addItem("Choisir");
               
               ListIterator<Article> it = liste.listIterator();
         while (it.hasNext())
         { 
             jComboBox1.addItem(it.next().getTitre().getValue());
         }
        
    }//GEN-LAST:event_ChargerBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
      
       
      int i = jComboBox1.getSelectedIndex();
      if (i<=0)
      {this.jTexte.setVisible(false);
       return;}
      
      this.jTexte.setVisible(true);
      
        Article articleSelectionne = liste.get(i-1);
        
        this.jTexte.setText(articleSelectionne.getTexte().getValue());
        

        this.jTextFieldDislikes.setText(articleSelectionne.getDislike().toString());
         this.jTextFieldLikes.setText(articleSelectionne.getLike().toString());
        this. btnDislike.setEnabled(true);
         this.btnLike.setEnabled(true);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        
       
        int i = jComboBox1.getSelectedIndex();
        Article articleSelectionne = liste.get(i-1);
        service.setLike(articleSelectionne.getTitre().getValue());
         btnDislike.setEnabled(false);
        

    }//GEN-LAST:event_btnLikeActionPerformed

    private void btnPremierArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierArticleActionPerformed
       
       
         Article articleSelectionne = liste.get(0);
         jComboBox1.setSelectedItem(articleSelectionne.getTitre().getValue());
        jTexte.setText(articleSelectionne.getTexte().getValue());

      jTextFieldLikes.setText(articleSelectionne.getLike().toString());
        jTextFieldDislikes.setText(articleSelectionne.getDislike().toString());
    }//GEN-LAST:event_btnPremierArticleActionPerformed

    private void btnDernierArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierArticleActionPerformed
        
        int i = liste.size() - 1;
           Article articleSelectionne = liste.get(i);
           jComboBox1.setSelectedItem(articleSelectionne.getTitre().getValue());
        jTexte.setText(articleSelectionne.getTexte().getValue());
       
        jTextFieldLikes.setText(articleSelectionne.getLike().toString());
        jTextFieldDislikes.setText(articleSelectionne.getDislike().toString());
    }//GEN-LAST:event_btnDernierArticleActionPerformed

    private void btnDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDislikeActionPerformed

        
        
         int i = jComboBox1.getSelectedIndex();
        Article articleSelectionne = liste.get(i-1);
        service.setDislike(articleSelectionne.getTitre().getValue());
         btnLike.setEnabled(false);
    }//GEN-LAST:event_btnDislikeActionPerformed

    private void btnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherActionPerformed
       
        jTexte.setVisible(true);
        
        String expression ;
        jComboBox1.removeAllItems();
        expression = jTextFieldRecherche.getText();
        
        liste =  service.setSearch(expression).getArticle();
       
         if(liste.isEmpty() )
       {
       JOptionPane.showMessageDialog(this, "Aucun article trouve");
      }
        jComboBox1.addItem("Choisir");
         ListIterator<Article> it = liste.listIterator();
         
         while (it.hasNext())
         {  
             jComboBox1.addItem(it.next().getTitre().getValue());
         }
         
         jTextFieldRecherche.setText(null);
          btnDislike.setEnabled(true);
         btnLike.setEnabled(true);
    }//GEN-LAST:event_btnChercherActionPerformed

    private void btnArticleSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleSuivantActionPerformed
        
      int i = jComboBox1.getSelectedIndex();
        i = i +1;
       int size = liste.size();
       if (i >= size)
        {  JOptionPane.showMessageDialog(this, "Il n'y a plus d'articles");}
        
       else 
       {
       Article articleSelectionne = liste.get(i-1);
           jComboBox1.setSelectedItem(articleSelectionne.getTitre().getValue());
        jTexte.setText(articleSelectionne.getTexte().getValue());
       
        jTextFieldLikes.setText(articleSelectionne.getLike().toString());
        jTextFieldDislikes.setText(articleSelectionne.getDislike().toString());
       }
       
      
    }//GEN-LAST:event_btnArticleSuivantActionPerformed

    private void btnArticlePrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticlePrecedentActionPerformed
      
    int i = jComboBox1.getSelectedIndex();
        i = i -1;
       
         if (i <= 0)
         
        {   JOptionPane.showMessageDialog(this, "Il n'y a plus d'articles");}
                
         else
         {
            Article articleSelectionne = liste.get(i-1);
               jComboBox1.setSelectedItem(articleSelectionne.getTitre().getValue());
            jTexte.setText(articleSelectionne.getTexte().getValue());

            jTextFieldLikes.setText(articleSelectionne.getLike().toString());
            jTextFieldDislikes.setText(articleSelectionne.getDislike().toString());
         }
        
        
    }//GEN-LAST:event_btnArticlePrecedentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChargerBtn;
    private javax.swing.JButton btnArticlePrecedent;
    private javax.swing.JButton btnArticleSuivant;
    private javax.swing.JButton btnChercher;
    private javax.swing.JButton btnDernierArticle;
    private javax.swing.JButton btnDislike;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnPremierArticle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDislikes;
    private javax.swing.JTextField jTextFieldLikes;
    private javax.swing.JTextField jTextFieldRecherche;
    private javax.swing.JTextArea jTexte;
    // End of variables declaration//GEN-END:variables

   
private List<Article> liste;
    private IService1 service = new Service1().getBasicHttpBindingIService1();

}
